name: Build Verification

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.3.1
      - name: Install, lint, and test
        run: |
          npm ci
          npm run lint --if-present
          npm test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '12.3.1'
      - name: Update hosts file
        run: echo '127.0.0.1 mssql mysql sfdc' | sudo tee --append /etc/hosts
      - name: pull images
        run: |
          docker pull glgresearch/sfdc-with-drakov:e04eea15
          docker pull microsoft/mssql-server-linux:2017-latest
          docker pull mysql:5.7.22
      - name: start docker containers
        run: docker-compose up --detach
      - name: make test
        env:
          CONNECTIONS: 'EPI_C_MSSQL_O EPI_C_MSSQL EPI_C_FILE EPI_C_MYSQL EPI_C_RENDER SFDC NON_EXISTENT_SERVER EPI_C_TIMESOUT EPI_C_MYSQL_BULK'
          DEBUG: true
          DIFFTEST_QUIET: false
          ENABLE_TEMPLATE_ACLS: DISABLED
          EPI_C_FILE: '{"driver":"file","config":{},"name":"file"}'
          EPI_C_MSSQL: '{"driver":"mssql","name":"mssql","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}'
          EPI_C_MSSQL_O: '{"driver":"mssql_o","name":"mssql_o","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}'
          EPI_C_MYSQL: '{"name":"mysql","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}'
          EPI_C_MYSQL_BULK: '{"name":"mysql_bulk", "type":"bulk","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}'
          EPI_C_RENDER: '{"driver":"render","config":{},"name":"render"}'
          EPI_C_TIMESOUT: '{"driver":"mssql","name":"timesout","config":{"server":"localhost","password":"vagrant","userName":"vagrant","options":{"port":1433, "requestTimeout":1}}}'
          EPI_SCREAMER_URL: https://services.glgresearch.com/epi-screamer/epiquery
          EPI_TEST_SERVER: localhost
          FORKS: 1
          LOCK_DIRECTORY: ~/tmp
          NODE_ENV: development
          NON_EXISTENT_SERVER: '{"driver":"mssql","name":"no_server","config":{"server":"no_server.pants.monkey.underware","password":"vagrant","userName":"vagrant","options":{"port":1433}}}'
          PORT: 8080
          SFDC: '{"name":"sfdc","driver":"salesforce","config":{"userName":"","password":"","server":"http://sfdc"}}'
          TEMPLATE_DIRECTORY: ${{ github.workspace }}/difftest/templates/
          URL_BASED_API_KEY: true
        run: |
          TZ=UTC make start &
          ./bin/wait-for-epi
          DEBUG= make test
