name: Build Verification

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.3.1
      - name: Install, lint, and test
        run: |
          npm ci
          npm run lint --if-present
          npm test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '12.3.1'
      - name: Update hosts file
        run: echo '127.0.0.1 mssql mysql sfdc' | sudo tee --append /etc/hosts
      - name: pull images
        run: |
          docker pull glgresearch/sfdc-with-drakov:e04eea15
          docker pull microsoft/mssql-server-linux:2017-latest
          docker pull mysql:5.7.22
      - name: start docker containers
        run: docker-compose up --detach
      - name: make test
        env:
          CONNECTION_CONFIG: '{"file":{"driver":"file","config":{},"name":"file"},"mssql":{"driver":"mssql","name":"mssql","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}},"mssql_o":{"driver":"mssql_o","name":"mssql_o","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}},"mysql":{"name":"mysql","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}},"mysql_bulk":{"name":"mysql_bulk", "type":"bulk","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}},"render":{"driver":"render","config":{},"name":"render"},"timeout":{"driver":"mssql","name":"timesout","config":{"server":"localhost","password":"vagrant","userName":"vagrant","options":{"port":1433, "requestTimeout":1}}},"no_server":{"driver":"mssql","name":"no_server","config":{"server":"no_server.pants.monkey.underware","password":"vagrant","userName":"vagrant","options":{"port":1433}}},"sfdc":{"name":"sfdc","driver":"salesforce","config":{"userName":"","password":"","server":"http://sfdc"}}}'
          DEBUG: true
          DIFFTEST_QUIET: false
          ENABLE_TEMPLATE_ACLS: DISABLED
          EPI_SCREAMER_URL: https://services.glgresearch.com/epi-screamer/epiquery
          EPI_TEST_SERVER: localhost
          FORKS: 1
          LOCK_DIRECTORY: ~/tmp
          NODE_ENV: development
          PORT: 8080
          TEMPLATE_DIRECTORY: ${{ github.workspace }}/difftest/templates/
          URL_BASED_API_KEY: true
        run: |
          TZ=UTC make start &
          ./bin/wait-for-epi
          DEBUG= make test
