name: Build Verification

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12.3.1
    services:
      mssql:
        image: microsoft/mssql-server-linux:2017-latest
        ports:
          - 1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourV3ryStrong!Passw0rd
      mysql:
        image: mysql:5.7.22
        ports:
          - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: epiquery
          MYSQL_ROOT_PASSWORD: mysql_root_password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
      sfdc:
        image: glgresearch/sfdc-with-drakov:e04eea15
        # volumes:
          # - ${{ github.workspace }}/mock-salesforce:/var/app
        ports:
          - 80
    steps:
      - uses: actions/checkout@v2
      - name: make test
        env:
          CONNECTIONS: 'EPI_C_FILE EPI_C_MSSQL_O EPI_C_MSSQL EPI_C_MYSQL_BULK EPI_C_MYSQL EPI_C_RENDER EPI_C_SFDC EPI_C_SNOWFLAKE EPI_C_TIMESOUT NON_EXISTENT_SERVER'
          DEBUG: true
          DIFFTEST_QUIET: false
          ENABLE_TEMPLATE_ACLS: DISABLED
          EPI_C_FILE: '{"driver":"file","name":"file","config":{}}'
          EPI_C_MSSQL_O: '{"driver":"mssql_o","name":"mssql_o","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":${{ job.services.mssql.ports[1433] }}, "requestTimeout":0}}}'
          EPI_C_MSSQL: '{"driver":"mssql","name":"mssql","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":${{ job.services.mssql.ports[1433] }},"requestTimeout":0}}}'
          EPI_C_MYSQL_BULK: '{"driver":"mysql","name":"mysql_bulk","type":"bulk","config":{"host":"mysql","user":"root","password":"mysql_root_password","port":${{ job.services.mysql.ports[3306] }}}}'
          EPI_C_MYSQL: '{"driver":"mysql","name":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password","port":${{ job.services.mysql.ports[3306] }}}}'
          EPI_C_RENDER: '{"driver":"render","name":"render","config":{}}'
          EPI_C_SFDC: '{"driver":"salesforce","name":"sfdc","config":{"userName":"","password":"","server":"http://sfdc:${{ job.services.sfdc.ports[80] }}"}}'
          EPI_C_SNOWFLAKE: '{"driver":"snowflake","name":"snowflake","config":{"account":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_ACCOUNT_ID }}", "warehouse":"EPIQUERY_PRODUCTION", "username":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_USERNAME }}", "password":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_PASSWORD }}"}}'
          EPI_C_TIMESOUT: '{"driver":"mssql","name":"timesout","config":{"server":"localhost","password":"vagrant","userName":"vagrant","options":{"port":1433, "requestTimeout":1}}}'
          EPI_SCREAMER_URL: https://services.glgresearch.com/epi-screamer/epiquery
          EPI_TEST_SERVER: localhost
          FORKS: 1
          LOCK_DIRECTORY: ~/tmp
          NODE_ENV: development
          NON_EXISTENT_SERVER: '{"driver":"mssql","name":"no_server","config":{"server":"no_server.pants.monkey.underware","password":"vagrant","userName":"vagrant","options":{"port":1433}}}'
          PORT: 8080
          TEMPLATE_DIRECTORY: ${{ github.workspace }}/difftest/templates/
        run: |
          TZ=UTC make start &
          ./bin/wait-for-epi
          DEBUG= make ci
